AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BrewlessMenuFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getMenu
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: ./
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          MAIN_CLASS: com.brewless.menu.MenuApplication
          MONGO_HOST: host.docker.internal

  BrewlessMenuFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/getMenu
      RetentionInDays: 7